"""utilization notes

Revision ID: b4e43e90a81f
Revises: 0d32800a2e28
Create Date: 2026-07-27 16:30:56.590957+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# Autogenerate renders custom column types by their full dotted path, so the module
# that defines them has to be importable here (app.models.types.UTCDateTime).
import app.models.types  # noqa: F401

revision: str = "b4e43e90a81f"
down_revision: str | None = "a1b2c3d4e5f6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "utilization_notes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("therapist_id", sa.Integer(), nullable=False),
        sa.Column("period_start", sa.Date(), nullable=False),
        sa.Column(
            "granularity",
            sa.Enum("week", "month", "quarter", name="granularity", native_enum=False, length=20),
            nullable=False,
        ),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("created_at", app.models.types.UTCDateTime(timezone=True), nullable=False),
        sa.Column("created_by_id", sa.Integer(), nullable=True),
        sa.Column("updated_at", app.models.types.UTCDateTime(timezone=True), nullable=False),
        sa.Column("updated_by_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["created_by_id"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["therapist_id"], ["therapists.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["updated_by_id"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "therapist_id", "period_start", "granularity", name="uq_utilization_note"
        ),
    )
    with op.batch_alter_table("utilization_notes", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_utilization_notes_period_start"), ["period_start"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_utilization_notes_therapist_id"), ["therapist_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("utilization_notes", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_utilization_notes_therapist_id"))
        batch_op.drop_index(batch_op.f("ix_utilization_notes_period_start"))

    op.drop_table("utilization_notes")
    # ### end Alembic commands ###
