"""rooms and room usage

Revision ID: 451550904b21
Revises: b4e43e90a81f
Create Date: 2026-07-27 16:46:21.086422+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# Autogenerate renders custom column types by their full dotted path, so the module
# that defines them has to be importable here (app.models.types.UTCDateTime).
import app.models.types  # noqa: F401

revision: str = "451550904b21"
down_revision: str | None = "b4e43e90a81f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "rooms",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("location_short", sa.String(length=40), nullable=True),
        sa.Column("default_slots_per_day", sa.Integer(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", app.models.types.UTCDateTime(timezone=True), nullable=False),
        sa.Column("updated_at", app.models.types.UTCDateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    with op.batch_alter_table("rooms", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_rooms_location_short"), ["location_short"], unique=False
        )

    op.create_table(
        "room_usage",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("room_id", sa.Integer(), nullable=False),
        sa.Column("usage_date", sa.Date(), nullable=False),
        sa.Column("slots_used", sa.Integer(), nullable=False),
        sa.Column("slots_available", sa.Integer(), nullable=False),
        sa.Column(
            "source",
            sa.Enum(
                "manual_upload", "manual_entry", name="usagesource", native_enum=False, length=30
            ),
            nullable=False,
        ),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("recorded_at", app.models.types.UTCDateTime(timezone=True), nullable=False),
        sa.Column("recorded_by_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["recorded_by_id"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["room_id"], ["rooms.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("room_id", "usage_date", name="uq_room_usage_day"),
    )
    with op.batch_alter_table("room_usage", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_room_usage_room_id"), ["room_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_room_usage_usage_date"), ["usage_date"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("room_usage", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_room_usage_usage_date"))
        batch_op.drop_index(batch_op.f("ix_room_usage_room_id"))

    op.drop_table("room_usage")
    with op.batch_alter_table("rooms", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_rooms_location_short"))

    op.drop_table("rooms")
    # ### end Alembic commands ###
