"""therapists carry discipline and personal expectations

Revision ID: fe6a0bc9d6dc
Revises: 3fc071e880c5
Create Date: 2026-07-29 02:54:30.245564+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# Autogenerate renders custom column types by their full dotted path, so the module
# that defines them has to be importable here (app.models.types.UTCDateTime).
import app.models.types  # noqa: F401

revision: str = "fe6a0bc9d6dc"
down_revision: str | None = "3fc071e880c5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "therapists",
        sa.Column(
            "discipline",
            sa.Enum("therapist", "psychiatrist", name="discipline", native_enum=False, length=20),
            server_default="therapist",
            nullable=False,
        ),
    )
    op.add_column("therapists", sa.Column("weekly_expected_sessions", sa.Integer(), nullable=True))
    # ### end Alembic commands ###

    # The practice's two psychiatrists appear in its exports as YOE and SHOR. Set
    # them here so the split is right on first deploy; the field stays editable in
    # the admin like everything else, so this is a starting value, not a constant.
    op.execute(
        """
        UPDATE therapists SET discipline = 'psychiatrist'
        WHERE id IN (
            SELECT therapist_id FROM therapist_aliases
            WHERE upper(alias) IN ('YOE', 'SHOR')
        )
        OR upper(display_name) IN ('YOE', 'SHOR')
        """
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("therapists", "weekly_expected_sessions")
    op.drop_column("therapists", "discipline")
    # ### end Alembic commands ###
