"""sync runs record the tab they read

Revision ID: 3fc071e880c5
Revises: 33b222d203da
Create Date: 2026-07-28 22:20:41.386058+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# Autogenerate renders custom column types by their full dotted path, so the module
# that defines them has to be importable here (app.models.types.UTCDateTime).
import app.models.types  # noqa: F401

revision: str = "3fc071e880c5"
down_revision: str | None = "33b222d203da"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("sync_runs", sa.Column("tab_name", sa.String(length=120), nullable=True))
    op.add_column("sync_runs", sa.Column("header_row", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sync_runs", "header_row")
    op.drop_column("sync_runs", "tab_name")
    # ### end Alembic commands ###
