"""Phase A profiler -- DISCOVER, DO NOT ASSUME.

Profiles whatever real exports are present in data/raw/ and rewrites the Part 1
"Observed inventory" of docs/data-dictionary.md with facts: per file, row count,
column names + inferred dtypes, detected date column(s) with observed min/max,
and inferred grain. **Only aggregates are emitted -- never a cell value** (the
PHI rule; the file is committed and public).

If data/raw/ is empty or lacks prior-year coverage for the target period, the
profiler does NOT fabricate data: it leaves docs/export-request.md as the
instruction to pull real exports and reports exactly what is short.

Determinism: files are processed in sorted order, columns in header order, and
no wall-clock or randomness enters the analysis path (ASSUMPTIONS §16).
"""
from __future__ import annotations

import argparse
import os
import sys
from dataclasses import dataclass, field
from datetime import datetime
from pathlib import Path
from typing import Dict, List, Optional, Sequence, Tuple

# Allow running as a script (python src/profile_raw.py) or as a module.
if __package__ in (None, ""):
    sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
    from src import loaders  # type: ignore
    from src.config import DEFAULT_CONFIG, Config
    from src.money import MoneyParseError, parse_money
    from src.periods import parse_period, prior_year_floor
else:
    from . import loaders
    from .config import DEFAULT_CONFIG, Config
    from .money import MoneyParseError, parse_money
    from .periods import parse_period, prior_year_floor


REPO_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_DATA_DIR = REPO_ROOT / "data" / "raw"
DEFAULT_DICT_PATH = REPO_ROOT / "docs" / "data-dictionary.md"

PROFILE_BEGIN = "<!-- PROFILE:BEGIN (regenerated by src/profile_raw.py) -->"
PROFILE_END = "<!-- PROFILE:END -->"

# Ordered, deterministic set of date formats to try. First match wins.
_DATE_FORMATS = (
    "%Y-%m-%d %H:%M:%S",
    "%Y-%m-%d %H:%M",
    "%Y-%m-%d",
    "%m/%d/%Y %I:%M:%S %p",
    "%m/%d/%Y %I:%M %p",
    "%m/%d/%Y %H:%M:%S",
    "%m/%d/%Y %H:%M",
    "%m/%d/%Y",
    "%m/%d/%y",
    "%d-%b-%Y",
    "%d-%b-%y",
)


def parse_date(value: str) -> Optional[datetime]:
    """Parse a date/datetime cell deterministically, or return None."""
    s = str(value).strip()
    if s == "":
        return None
    for fmt in _DATE_FORMATS:
        try:
            return datetime.strptime(s, fmt)
        except ValueError:
            continue
    return None


def _is_int(s: str) -> bool:
    s = str(s).strip()
    if s == "":
        return False
    if s[0] in "+-":
        s = s[1:]
    return s.isdigit()


# A column is classified by its DOMINANT cell type; a few dirty cells no longer
# downgrade the whole column (defect: one N/A killed a 40k-row date column). The
# non-conforming cells are counted and reported, never silently absorbed.
DOMINANT_THRESHOLD = 0.90


@dataclass
class ColumnProfile:
    name: str
    dtype: str  # date | int | decimal | code | string | empty
    n_nonempty: int
    n_empty: int
    n_distinct: int  # aggregate count only -- never the values themselves
    n_nonconforming: int = 0  # cells not of the reported dtype (counted, reported)
    date_min: Optional[str] = None  # ISO string, aggregate extremum, PHI-safe
    date_max: Optional[str] = None


@dataclass
class FileProfile:
    filename: str
    family: Optional[str]
    n_rows: int
    columns: List[ColumnProfile]
    date_columns: List[str] = field(default_factory=list)
    dos_column: Optional[str] = None
    dos_min: Optional[str] = None
    dos_max: Optional[str] = None
    posting_column: Optional[str] = None
    has_posting: bool = False
    grain: str = ""
    grain_confirmed: Optional[bool] = None
    n_distinct_keys: Optional[int] = None
    notes: List[str] = field(default_factory=list)


def _cell_type(s: str) -> str:
    """Type of a single non-empty cell: date | int | decimal | string."""
    s = str(s).strip()
    if _is_int(s):
        return "int"  # check int before date so a bare "2024" is not a date
    if parse_date(s) is not None and ("/" in s or "-" in s) and len(s) >= 6:
        return "date"
    try:
        if parse_money(s) is not None:
            return "decimal"
    except MoneyParseError:
        pass
    return "string"


def _classify_column(
    cells: Sequence[str], threshold: float = DOMINANT_THRESHOLD
) -> Tuple[str, int]:
    """Return (dtype, n_nonconforming) using a dominant-type threshold.

    int and decimal combine (a mostly-money column with a few whole-dollar ints
    is still money). If no clean type reaches the threshold the column is a
    string; n_nonconforming counts the cells that did not fit the reported type.
    """
    nonempty = [str(c) for c in cells if str(c).strip() != ""]
    if not nonempty:
        return ("empty", 0)
    counts = {"date": 0, "int": 0, "decimal": 0, "string": 0}
    for c in nonempty:
        counts[_cell_type(c)] += 1
    total = len(nonempty)

    if counts["date"] / total >= threshold:
        return ("date", total - counts["date"])
    numeric = counts["int"] + counts["decimal"]
    if numeric / total >= threshold:
        dtype = "int" if counts["decimal"] == 0 else "decimal"
        return (dtype, total - numeric)
    return ("string", total - counts["string"])


def _profile_column(name: str, cells: Sequence[str], family: Optional[str]) -> ColumnProfile:
    nonempty = [str(c) for c in cells if str(c).strip() != ""]
    dtype, n_nonconforming = _classify_column(cells)
    # CPT/HCPCS/transaction codes are opaque strings by NAME, never numeric-coerced
    # (a code like '0362T' or a leading-zero HCPCS must survive).
    if family is not None and loaders.is_code_column(family, name):
        dtype, n_nonconforming = "code", 0
    date_min = date_max = None
    if dtype == "date":
        parsed = [d for d in (parse_date(c) for c in nonempty) if d is not None]
        if parsed:
            date_min = min(parsed).isoformat(sep=" ")
            date_max = max(parsed).isoformat(sep=" ")
    return ColumnProfile(
        name=name,
        dtype=dtype,
        n_nonempty=len(nonempty),
        n_empty=len(cells) - len(nonempty),
        n_distinct=len(set(nonempty)),  # count only; values never leave memory
        n_nonconforming=n_nonconforming,
        date_min=date_min,
        date_max=date_max,
    )


def _find_col(header: Sequence[str], token: str) -> Optional[str]:
    tnorm = loaders._norm_alnum(token)
    for h in header:
        if tnorm and tnorm in loaders._norm_alnum(h):
            return h
    return None


def profile_file(path: str) -> FileProfile:
    """Profile a single raw export into aggregate-only facts.

    An unrecognized file does not crash the run: it yields a FileProfile with
    family=None that lands in the exceptions bucket.
    """
    filename = os.path.basename(path)
    family = loaders.classify_filename(path)

    # Defect: an unrecognized file hard-crashed the run. Route it to the bucket.
    if family is None:
        return FileProfile(
            filename=filename,
            family=None,
            n_rows=0,
            columns=[],
            grain="unknown (unrecognized report family)",
            notes=["filename did not match any known Valant report prefix; "
                   "routed to the exceptions bucket, not profiled"],
        )

    header, records = loaders.load_report(path, family=family)

    columns = [
        _profile_column(name, [rec.get(name, "") for rec in records], family)
        for name in header
    ]
    date_cols = [c.name for c in columns if c.dtype == "date"]

    fp = FileProfile(
        filename=filename,
        family=family,
        n_rows=len(records),
        columns=columns,
        date_columns=date_cols,
    )

    # Date of service: resolve the EXPLICIT per-family DOS column. Never a bare
    # "date" fallback, so a posting/appointment date can't masquerade as DOS.
    try:
        fp.dos_column = loaders.resolve_dos_column(family, header)
    except loaders.MissingColumnsError as e:
        fp.notes.append(str(e))
    if fp.dos_column is not None:
        col = next((c for c in columns if c.name == fp.dos_column), None)
        if col is not None and col.dtype == "date":
            fp.dos_min, fp.dos_max = col.date_min, col.date_max
        elif col is not None:
            fp.notes.append(
                f"DOS column {fp.dos_column!r} did not parse as a date "
                f"(dtype={col.dtype}, {col.n_nonconforming} non-conforming cells)"
            )

    # Posting/payment date is a SEPARATE column (statements) and must never be
    # confused with DOS. Record its presence for the Phase C maturity model.
    fp.posting_column = loaders.resolve_posting_column(family, header)
    fp.has_posting = fp.posting_column is not None
    if family == "statements" and not fp.has_posting:
        fp.notes.append(
            "no posting/payment-date column found -- the Phase C claim-lag "
            "maturity model cannot be built without it"
        )

    # Grain: documented expectation, and for charges a real 1:1 confirmation via a
    # composite key (counts only; the key values never leave memory -- §17).
    fp.grain = str(loaders.REPORT_FAMILIES[family]["expected_grain"]) + " (expected)"
    if family == "charges":
        # Short tokens so they match both engine canonical names (PatientID,
        # CPTCode, ...) and simpler export headers (Patient, CPT/HCPCS Code, ...).
        key_tokens = ["Patient", "Provider", "DateOfService", "CPT", "Modifier"]
        key_cols = [c for c in (_find_col(header, t) for t in key_tokens) if c]
        if len(key_cols) >= 3:
            keys = {
                tuple(loaders._norm_alnum(rec.get(k, "")) for k in key_cols)
                for rec in records
            }
            fp.n_distinct_keys = len(keys)
            fp.grain_confirmed = fp.n_distinct_keys == fp.n_rows
            fp.grain = (
                "one row per charge line "
                f"[{' x '.join(key_cols)}] -- "
                + ("confirmed" if fp.grain_confirmed else "NOT 1:1 (duplicates present)")
            )

    return fp


def discover_files(data_dir: Path) -> List[Path]:
    """Sorted list of candidate export files in data_dir (deterministic)."""
    if not data_dir.exists():
        return []
    out = []
    for p in sorted(data_dir.iterdir(), key=lambda x: x.name):
        if p.name == ".gitkeep" or p.name.startswith("."):
            continue
        if p.suffix.lower() in (".csv", ".txt", ".tsv", ".xlsx", ".xlsm"):
            out.append(p)
    return out


def check_prior_year_coverage(
    profiles: Sequence[FileProfile], period: str
) -> Tuple[bool, str]:
    """Do the dated files reach at least one year before the target period?"""
    floor = prior_year_floor(period)
    dated = [(fp.filename, fp.dos_min) for fp in profiles if fp.dos_min]
    if not dated:
        return False, "no file exposed a parseable date-of-service column"
    earliest_name, earliest_str = min(dated, key=lambda t: t[1])
    earliest = datetime.fromisoformat(earliest_str)
    ok = earliest <= floor
    detail = (
        f"earliest observed DOS {earliest.date().isoformat()} "
        f"({earliest_name}) vs required <= {floor.date().isoformat()}"
    )
    return ok, detail


def render_part1(
    profiles: Sequence[FileProfile],
    period: str,
    coverage: Optional[Tuple[bool, str]],
    unrecognized: Sequence[str],
) -> str:
    """Render the Part 1 observed-inventory block (aggregates only)."""
    lines: List[str] = [PROFILE_BEGIN, ""]
    lines.append("## Part 1 -- Observed inventory")
    lines.append("")
    lines.append(
        "_Regenerated by `src/profile_raw.py`. Aggregates only: row counts, "
        "column names, inferred dtypes, and date extrema. No cell values, ever._"
    )
    lines.append("")

    if not profiles:
        lines.append(
            "**Status: `data/raw/` is EMPTY** (only `.gitkeep`). Nothing to profile. "
            "Per the spec the pipeline stops and defers to "
            "[`export-request.md`](export-request.md) rather than fabricating data."
        )
        lines.append("")
        lines.append("| filename | rows | date col(s) | date range (observed) | grain |")
        lines.append("|---|---|---|---|---|")
        lines.append("| _none present_ | -- | -- | -- | -- |")
        lines.append("")
        lines.append(PROFILE_END)
        return "\n".join(lines)

    lines.append(f"**Target period:** `{period}`  ")
    if coverage is not None:
        ok, detail = coverage
        label = "OK" if ok else "**INSUFFICIENT**"
        lines.append(f"**Prior-year coverage:** {label} -- {detail}")
    lines.append("")
    lines.append("| filename | family | rows | date col(s) | DOS range | grain |")
    lines.append("|---|---|---|---|---|---|")
    for fp in profiles:
        dos = (
            f"{fp.dos_min} .. {fp.dos_max}"
            if fp.dos_min and fp.dos_max
            else "--"
        )
        datecols = ", ".join(fp.date_columns) if fp.date_columns else "--"
        lines.append(
            f"| `{fp.filename}` | {fp.family or 'UNRECOGNIZED'} | {fp.n_rows} "
            f"| {datecols} | {dos} | {fp.grain} |"
        )
    lines.append("")

    for fp in profiles:
        lines.append(f"### `{fp.filename}`")
        if fp.dos_column:
            lines.append(f"- Date-of-service column: `{fp.dos_column}`")
        if fp.posting_column:
            lines.append(f"- Posting/payment-date column: `{fp.posting_column}`")
        if fp.grain_confirmed is not None:
            lines.append(
                f"- Grain 1:1 check: **{fp.grain_confirmed}** "
                f"(rows={fp.n_rows}, distinct keys={fp.n_distinct_keys})"
            )
        lines.append("")
        lines.append(
            "| column | dtype | non-empty | empty | distinct | non-conf | "
            "date min | date max |"
        )
        lines.append("|---|---|---:|---:|---:|---:|---|---|")
        for c in fp.columns:
            lines.append(
                f"| {c.name} | {c.dtype} | {c.n_nonempty} | {c.n_empty} "
                f"| {c.n_distinct} | {c.n_nonconforming} "
                f"| {c.date_min or ''} | {c.date_max or ''} |"
            )
        if fp.notes:
            lines.append("")
            for n in fp.notes:
                lines.append(f"> note: {n}")
        lines.append("")

    if unrecognized:
        lines.append("### Unrecognized files (exceptions bucket)")
        for name in unrecognized:
            lines.append(f"- `{name}` -- no known Valant report prefix; not profiled as a family")
        lines.append("")

    lines.append(PROFILE_END)
    return "\n".join(lines)


def _splice_into_dictionary(dict_path: Path, block: str) -> None:
    """Replace the region between the PROFILE markers, or append it if absent."""
    if dict_path.exists():
        text = dict_path.read_text(encoding="utf-8")
    else:
        text = "# Data Dictionary -- SRI Practice Health Analytics\n"
    if PROFILE_BEGIN in text and PROFILE_END in text:
        pre = text.split(PROFILE_BEGIN)[0]
        post = text.split(PROFILE_END, 1)[1]
        text = pre + block + post
    else:
        text = text.rstrip() + "\n\n" + block + "\n"
    dict_path.write_text(text, encoding="utf-8")


def run(
    data_dir: Path = DEFAULT_DATA_DIR,
    dict_path: Path = DEFAULT_DICT_PATH,
    config: Config = DEFAULT_CONFIG,
    write: bool = True,
) -> Dict[str, object]:
    """Profile data_dir and (optionally) splice results into the data dictionary.

    Returns a summary dict of aggregates -- safe to print. Never returns or logs
    any cell value.
    """
    period = config.target_period
    parse_period(period)  # validate early

    files = discover_files(Path(data_dir))
    profiles: List[FileProfile] = []
    unrecognized: List[str] = []
    for p in files:
        fp = profile_file(str(p))
        profiles.append(fp)
        if fp.family is None:
            unrecognized.append(fp.filename)

    coverage = check_prior_year_coverage(profiles, period) if profiles else None

    block = render_part1(profiles, period, coverage, unrecognized)
    if write:
        _splice_into_dictionary(Path(dict_path), block)

    status = "EMPTY" if not profiles else (
        "OK" if (coverage and coverage[0]) else "INSUFFICIENT_COVERAGE"
    )
    return {
        "status": status,
        "n_files": len(files),
        "n_recognized": len(profiles) - len(unrecognized),
        "n_unrecognized": len(unrecognized),
        "target_period": period,
        "coverage_ok": bool(coverage[0]) if coverage else False,
        "coverage_detail": coverage[1] if coverage else "no data present",
        "rules_md_reconciled": config.rules_md_reconciled,
        "rules_reconciled": tuple(sorted(config.rules_reconciled)),
        "rules_unreconciled": config.unreconciled_sections(),
    }


def main(argv: Optional[Sequence[str]] = None) -> int:
    ap = argparse.ArgumentParser(description="SRI Phase A profiler (aggregate-only).")
    ap.add_argument("--data-dir", default=str(DEFAULT_DATA_DIR))
    ap.add_argument("--dict", default=str(DEFAULT_DICT_PATH))
    ap.add_argument("--period", default=DEFAULT_CONFIG.target_period)
    ap.add_argument("--no-write", action="store_true", help="profile but do not edit docs")
    args = ap.parse_args(argv)

    cfg = Config(target_period=args.period)
    summary = run(
        data_dir=Path(args.data_dir),
        dict_path=Path(args.dict),
        config=cfg,
        write=not args.no_write,
    )
    print("Phase A profile summary (aggregates only):")
    for k, v in summary.items():
        print(f"  {k}: {v}")
    if summary["status"] == "EMPTY":
        print(
            "\ndata/raw/ is empty -- no data fabricated. See docs/export-request.md "
            "for exactly what to pull, then re-run."
        )
    elif summary["status"] == "INSUFFICIENT_COVERAGE":
        print(
            "\nData present but prior-year coverage is short. Phases B-F stay "
            "blocked until coverage is met -- see docs/export-request.md."
        )
    if summary["rules_unreconciled"]:
        print(
            "\nNOTE: these engine-flagged sections are NOT yet reconciled: "
            f"{', '.join(summary['rules_unreconciled'])}. They use documented defaults "
            "(ASSUMPTIONS §0)."
        )
    else:
        print(
            "\nNOTE: roster/period/code DEFINITIONS are reconciled against the engine "
            "(Gate 0). Implementation of them lands in Gates 1-3, and headline numbers "
            "still require real data in data/raw/ (ASSUMPTIONS §0)."
        )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
